### ISSUE TITLE
[Bug] Module build failed

### ISSUE THREAD

**Issue by brianwong3** [creativetimofficial/ct-nuxt-argon-dashboard-pro#9] opened 2019-11-27 06:00 UTC
### Version
v1.1.1
### Reproduction link
https://codepen.io/
### Operating System
WIndows 10
### Device
Laptop
### Browser & Version
Chrome v78
### Steps to reproduce
1. Extract zip and cd into it
2. run npm install
3. run npm run dev
### What is expected?
for it to build successfully
### What is actually happening?
getting an error - Wrong number of arguments ( 1 for 0 ) for 'form-control-focus'

---

**Comment by MichelleCCHo** [comment] 2019-12-03 03:24
Encountered the same build error.

**Comment by egulbrand** [comment] 2019-12-03 11:37
I am getting the same error also.

**Comment by egulbrand** [comment] 2019-12-03 11:46
Just wanted to comment that running 'yarn install' and 'yarn dev' does work.

**Comment by bbaltutat** [comment] 2019-12-04 04:03
same

**Comment by bbaltutat** [comment] 2019-12-04 17:48
@egulbrand  are you able to yum update and still have it work?

-----

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                                                                                                                                                       friendly-errors 11:46:57  
SassError: wrong number of arguments (1 for 0) for `form-control-focus'
        on line 40 of node_modules/bootstrap/scss/_forms.scss, in mixin `form-control-focus`
        from line 40 of node_modules/bootstrap/scss/_forms.scss
        from line 41 of C:\Users\xxxx\Documents\VisualStudioCode\xxxx\assets\sass\argon.scss
>>   @include form-control-focus($ignore-warning: true);

friendly-errors 11:46:57  
 @ ./assets/sass/argon.scss 4:14-225 14:3-18:5 15:22-233
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js

**Comment by cristijora** [comment] 2019-12-05 10:10
Hello everyone. Seems like this is an error caused by a new version of bootstrap.
@brianwong3 @MichelleCCHo @egulbrand @bbaltutat 
As a fix please change this 
`"bootstrap": "^4.3.1"` to this `"bootstrap": "4.3.1"` 
in package json.

Npm especially will install the latest version of bootstrap which is 4.4.1 and has some changes in the sass files. Making sure you install 4.3.1 will fix the issue
Longer term we will make some updates and make sure version 4.4.1 is also supported and working but for now please lock the bootstrap version and use 4.3.1. 

Sorry for any inconveniences caused. We will do a small update and lock many of the dependencies (to fixed versions) to avoid similar issues in the future.

**Comment by cristijora** [comment] 2020-01-05 15:12
This issue was fixed in version 1.2.0 along with other fixes & improvements.
For more details check the detailed [changelog here](https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/changelog.html)

**Closed as completed by cristijora** 2020-01-05 15:12 UTC
